apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: rest-api
        image: locahost:5000/simple-node-app
        ports:
        - name: nodejs-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
